import { AdminResourcesService } from './adminResourcesService';
import { UserBookingsService } from './userBookingsService';
import { UserPlacementsService } from './userPlacementsService';
import { AdminUsersService } from './adminUsersService';
import { UserAccountsService } from './userAccountsService';
import { UserService } from './userService';
import { HealthCheckService } from './healthCheckService';
import { SysAccountsService } from './sysAccountsService';
import { SysUsersService } from './sysUsersService';
export declare const Services: (typeof AdminResourcesService | typeof AdminUsersService | typeof HealthCheckService | typeof UserBookingsService | typeof UserPlacementsService | typeof UserAccountsService | typeof UserService | typeof SysAccountsService | typeof SysUsersService)[];
