import { HealthCheckService } from './healthCheckService';
import { SysAccountsService } from './sysAccountsService';
import { SysUsersService } from './sysUsersService';
import { AdminResourcesService } from './adminResourcesService';
import { UserBookingsService } from './userBookingsService';
import { UserPlacementsService } from './userPlacementsService';
import { UsersService } from './usersService';
import { UserAccountsService } from './userAccountsService';
import { UserService } from './userService';
export declare const Services: (typeof AdminResourcesService | typeof HealthCheckService | typeof SysAccountsService | typeof SysUsersService | typeof UserBookingsService | typeof UserPlacementsService | typeof UsersService | typeof UserAccountsService | typeof UserService)[];
